spring:
    application:
        name: service

server:
    port: 8081

service:
    instance:
        name: First Service            

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
