spring:
    application:
        name: client

server:
    port: 5001   

eureka:
    client:
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:8761/eureka

