spring:
    application:
        name: service

server:
    port: 8082

service:
    instance:
        name: second service module            

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

